=== DiogoM14/colege/peid/aula2/ex03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root-element">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Empresa" type="EmpresaType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="Departamento" type="DepartamentoType"></xs:element>

  <xs:element name="Funcionario" type="FuncionarioType" />

  <xs:complexType name="FuncionariosType">
    <xs:sequence>
      <xs:element ref="Funcionario" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DepartamentosType">
    <xs:sequence>
      <xs:element ref="Departamento" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DepartamentoType">
    <xs:sequence>
      <xs:element name="Designação" type="xs:string" />
      <xs:element name="Telefone" type="xs:integer" />
      <xs:element name="E-mail" type="xs:string" />
      <xs:element name="idDep" type="xs:string" />

      <xs:element name="Funcionarios" type="FuncionariosType" />

    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" />
  </xs:complexType>

  <xs:complexType name="FuncionarioType">
    <xs:sequence>
      <xs:element name="Nome" type="xs:string" />
      <xs:element name="Morada" type="xs:string" />
      <xs:element name="E-mail" type="xs:string" />
      <xs:element name="nrFunc" type="xs:string" />

    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" />
  </xs:complexType>

  <xs:complexType name="EmpresaType">
    <xs:sequence>
      <xs:element name="Designação" type="xs:string" />
      <xs:element name="Localidade" type="xs:string" />
      <xs:element name="Departamentos" type="DepartamentosType" />
    </xs:sequence>

    <xs:attribute name="id" type="xs:integer" />
  </xs:complexType>
</xs:schema>

=== DiogoM14/colege/peid/aula2/ex03.xml
<?xml version="1.0" encoding="UTF-8"?>
<root-element
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ex03.xsd"
>
  <Empresa>
    <Designação>Empresa X</Designação>
    <Localidade></Localidade>

    <Departamentos>
      <Departamento>
        <Designação></Designação>
        <Telefone>213</Telefone>
        <E-mail></E-mail>
        <idDep></idDep>

        <Funcionarios>
          <Funcionario>
            <Nome></Nome>
            <Morada></Morada>
            <E-mail></E-mail>
            <nrFunc></nrFunc>
          </Funcionario>
        </Funcionarios>

      </Departamento>
    </Departamentos>
    
  </Empresa>
</root-element>
